version: "3.8"

services:
  app:
    build: .
    container_name: rent_api
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app
    depends_on:
      - db_postgres
    links:
      - db_postgres

  db_postgres:
    image: postgres
    container_name: database_rent_api
    restart: always
    ports:
      - 5442:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: rent_api_db
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
