version: "3.8"

services:
  app:
    build: .
    container_name: rent_api
    environment:
      NODE_ENV: docker
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app
    depends_on:
      - db_postgres
    links:
      - db_postgres

  db_postgres:
    image: postgres
    container_name: database_rent_api
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    volumes:
      - pgdata:/data/postgres
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
    driver: local
